#!/usr/bin/env ruby

require "io/console"
require "open3"

hosts = File.read("hosts").strip.split(?\n).map{|x| x.split }

def run_itamae(host, node_json, roles)
  puts "itamae ssh -h #{host} -j #{node_json} -l debug #{roles.join(?\s)}"

  # puts "Execute: #{cmd}"

  # Open3.popen3(cmd) do |i, o, t|
  #   tin = Thread.new do
  #     i.puts sudo_password
  #     # i.close
  #   end

  #   tout = Thread.new do
  #     while line = o.gets
  #       puts "=> #{line}"
  #     end
  #     i.close
  #   end

  #   tin.join
  #   tout.join
  # end
end

if ARGV.length < 2
  puts "#{$0} [hostname or `all`] [roles...]"
  exit
end

if ARGV[0] == "all"
  hosts.each do |x|
    hostname, node = x
    run_itamae(hostname, node, ARGV[1..-1])
  end
else
  host = hosts.select{|x| x[0] == ARGV[0] }
  if host.nil?
    puts "specified host not found"
    exit
  end

  hostname, node = host[0]
  run_itamae(hostname, node, ARGV[1..-1])
end
