recipes_relative_path = "../recipes"

include_recipe "#{recipes_relative_path}/update-hosts"
include_recipe "#{recipes_relative_path}/setup-midonet-repositories"
include_recipe "#{recipes_relative_path}/set-selinux-permissive"
include_recipe "#{recipes_relative_path}/install-chrony"
include_recipe "#{recipes_relative_path}/install-openstack-packages"
include_recipe "#{recipes_relative_path}/install-mariadb"
include_recipe "#{recipes_relative_path}/install-mongodb"
include_recipe "#{recipes_relative_path}/install-rabbitmq"
include_recipe "#{recipes_relative_path}/install-memcached"
include_recipe "#{recipes_relative_path}/install-openstack-keystone"
include_recipe "#{recipes_relative_path}/setup-accounts"
include_recipe "#{recipes_relative_path}/setup-midonet-to-keystone"
include_recipe "#{recipes_relative_path}/install-openstack-glance"
include_recipe "#{recipes_relative_path}/install-openstack-nova-controller"
include_recipe "#{recipes_relative_path}/setup-midonet-to-nova"
include_recipe "#{recipes_relative_path}/install-openstack-neutron-with-midonet-controller"
include_recipe "#{recipes_relative_path}/install-openstack-horizon"
include_recipe "#{recipes_relative_path}/install-midonet-fwaas-controller"
include_recipe "#{recipes_relative_path}/install-midonet-lbaas-controller"
include_recipe "#{recipes_relative_path}/install-midonet-nsdb-zookeeper"
include_recipe "#{recipes_relative_path}/install-midonet-nsdb-cassandra"
include_recipe "#{recipes_relative_path}/install-midonet-cluster"
include_recipe "#{recipes_relative_path}/install-midonet-cli"
include_recipe "#{recipes_relative_path}/install-midonet-midolman"
